name: CI/CD Deployment

on:
  push:
    branches:
      - dev
      - testing
      - uat
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t satti507/glowante:${{ github.ref_name }} .
          docker push satti507/glowante:${{ github.ref_name }}

      - name: SSH and Deploy on EC2
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.AWS_EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.AWS_EC2_KEY }}
          script: |
            docker pull satti507/glowante:${{ github.ref_name }}
            docker stop glowante || true
            docker rm glowante || true
            docker run -d -p 3000:3000 --name glowante satti507/glowante:${{ github.ref_name }}
